services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
     - "443:443"
    restart: unless-stopped
    volumes:
     - wordpress:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - CERTS_=${CERTS_}
      - CERTS_KEY_=${CERTS_KEY_}
    depends_on:
      - wordpress
      - mariadb
    networks:
      inception:
  
  mariadb: 
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${db_name}
      - MYSQL_USER=${db_user}
      - MYSQL_PASSWORD=${db_pwd}
      - MYSQL_ROOT_PASSWORD=${db_pwd}
    networks:
       inception:
  
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USR=${WP_ADMIN_USR}
      - WP_ADMIN_PWD=${WP_ADMIN_PWD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USR=${WP_USR}
      - WP_EMAIL=${WP_EMAIL}
      - WP_PWD=${WP_PWD}
      - DB_NAME=${db_name}
      - DB_USER=${db_user}
      - DB_PASSWORD=${db_pwd}
      - DB_HOST=${db_host}
    depends_on:
      - mariadb
    networks:
      inception:

volumes:
  mariadb:
    driver: local
    driver_opts:
     type: 'none'
     o: 'bind'
     device: '/home/${USER}/data/mariadb'

  wordpress:
    driver: local
    driver_opts:
     type: 'none'
     o: 'bind'
     device: '/home/${USER}/data/wordpress'

networks:
  inception:
   name: inception
